//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ami_Common_Service
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestToken", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class RequestToken : object
    {
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestStatus", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class RequestStatus : object
    {
        
        private Ami_Common_Service.RequestToken RequestTokenField;
        
        private Ami_Common_Service.State StateField;
        
        private int EndpointsScheduledField;
        
        private Ami_Common_Service.Result ResultField;
        
        private int SuccessfulEndpointsField;
        
        private int FailedEndpointsField;
        
        private System.DateTime CreatedWhenField;
        
        private System.Nullable<System.DateTime> FinishedWhenField;
        
        private System.Xml.XmlNode[] MetadataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Ami_Common_Service.RequestToken RequestToken
        {
            get
            {
                return this.RequestTokenField;
            }
            set
            {
                this.RequestTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Ami_Common_Service.State State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int EndpointsScheduled
        {
            get
            {
                return this.EndpointsScheduledField;
            }
            set
            {
                this.EndpointsScheduledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public Ami_Common_Service.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int SuccessfulEndpoints
        {
            get
            {
                return this.SuccessfulEndpointsField;
            }
            set
            {
                this.SuccessfulEndpointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int FailedEndpoints
        {
            get
            {
                return this.FailedEndpointsField;
            }
            set
            {
                this.FailedEndpointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime CreatedWhen
        {
            get
            {
                return this.CreatedWhenField;
            }
            set
            {
                this.CreatedWhenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public System.Nullable<System.DateTime> FinishedWhen
        {
            get
            {
                return this.FinishedWhenField;
            }
            set
            {
                this.FinishedWhenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public System.Xml.XmlNode[] Metadata
        {
            get
            {
                return this.MetadataField;
            }
            set
            {
                this.MetadataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://www.itron.com/ami/2008/10/common")]
    public enum State : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Initializing = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Executing = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://www.itron.com/ami/2008/10/common")]
    public enum Result : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.TooManyConcurrentRequestsFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.DeviceNotFoundFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.DuplicateSubscriberEndpointFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.DuplicateSubscriberFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.DuplicateSubscriptionFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.EndpointNotFoundFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.EndpointNotRegisteredFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.GroupNotFoundFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.InvalidDateTimeRangeFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.InvalidUriFormatFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.MeterNotFoundFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.MeterNotRegisteredFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.OperationNotSupportedFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.NoValidTargetsFoundFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.RequestNotFinishedFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.RequestNotFoundFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.SubscriberEndpointNotFoundFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.SubscriberNotFoundFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.TooManyCommandsFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.TooManySubscribersFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.InvalidPermissionLevelFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.InvalidOpticalUserIdFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.InvalidAuthorizationClassFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.InvalidRequestedServiceFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.InvalidAuthorizationPrincipalFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.InvalidAuthorizationRightsFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ami_Common_Service.ArgumentFault))]
    public partial class OperationFault : object
    {
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TooManyConcurrentRequestsFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class TooManyConcurrentRequestsFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceNotFoundFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class DeviceNotFoundFault : Ami_Common_Service.OperationFault
    {
        
        private ulong MacAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong MacAddress
        {
            get
            {
                return this.MacAddressField;
            }
            set
            {
                this.MacAddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DuplicateSubscriberEndpointFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class DuplicateSubscriberEndpointFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DuplicateSubscriberFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class DuplicateSubscriberFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DuplicateSubscriptionFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class DuplicateSubscriptionFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndpointNotFoundFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class EndpointNotFoundFault : Ami_Common_Service.OperationFault
    {
        
        private string IdentifierField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndpointNotRegisteredFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class EndpointNotRegisteredFault : Ami_Common_Service.OperationFault
    {
        
        private string IdentifierField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupNotFoundFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class GroupNotFoundFault : Ami_Common_Service.OperationFault
    {
        
        private string GroupNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName
        {
            get
            {
                return this.GroupNameField;
            }
            set
            {
                this.GroupNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidDateTimeRangeFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class InvalidDateTimeRangeFault : Ami_Common_Service.OperationFault
    {
        
        private System.DateTime StartField;
        
        private System.DateTime EndField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Start
        {
            get
            {
                return this.StartField;
            }
            set
            {
                this.StartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime End
        {
            get
            {
                return this.EndField;
            }
            set
            {
                this.EndField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidUriFormatFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class InvalidUriFormatFault : Ami_Common_Service.OperationFault
    {
        
        private System.Uri UriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri Uri
        {
            get
            {
                return this.UriField;
            }
            set
            {
                this.UriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeterNotFoundFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class MeterNotFoundFault : Ami_Common_Service.OperationFault
    {
        
        private string ElectronicSerialNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ElectronicSerialNumber
        {
            get
            {
                return this.ElectronicSerialNumberField;
            }
            set
            {
                this.ElectronicSerialNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeterNotRegisteredFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class MeterNotRegisteredFault : Ami_Common_Service.OperationFault
    {
        
        private string ElectronicSerialNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ElectronicSerialNumber
        {
            get
            {
                return this.ElectronicSerialNumberField;
            }
            set
            {
                this.ElectronicSerialNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationNotSupportedFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class OperationNotSupportedFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoValidTargetsFoundFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class NoValidTargetsFoundFault : Ami_Common_Service.OperationFault
    {
        
        private Ami_Common_Service.EndpointFailure[] InvalidEndpointsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Ami_Common_Service.EndpointFailure[] InvalidEndpoints
        {
            get
            {
                return this.InvalidEndpointsField;
            }
            set
            {
                this.InvalidEndpointsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestNotFinishedFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class RequestNotFinishedFault : Ami_Common_Service.OperationFault
    {
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestNotFoundFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class RequestNotFoundFault : Ami_Common_Service.OperationFault
    {
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriberEndpointNotFoundFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class SubscriberEndpointNotFoundFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriberNotFoundFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class SubscriberNotFoundFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TooManyCommandsFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class TooManyCommandsFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TooManySubscribersFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class TooManySubscribersFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidPermissionLevelFault", Namespace="http://www.itron.com/ami/2009/12/security")]
    public partial class InvalidPermissionLevelFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidOpticalUserIdFault", Namespace="http://www.itron.com/ami/2009/12/security")]
    public partial class InvalidOpticalUserIdFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidAuthorizationClassFault", Namespace="http://www.itron.com/ami/2014/12/security")]
    public partial class InvalidAuthorizationClassFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidRequestedServiceFault", Namespace="http://www.itron.com/ami/2014/12/security")]
    public partial class InvalidRequestedServiceFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidAuthorizationPrincipalFault", Namespace="http://www.itron.com/ami/2014/12/security")]
    public partial class InvalidAuthorizationPrincipalFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidAuthorizationRightsFault", Namespace="http://www.itron.com/ami/2014/12/security")]
    public partial class InvalidAuthorizationRightsFault : Ami_Common_Service.OperationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArgumentFault", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class ArgumentFault : Ami_Common_Service.OperationFault
    {
        
        private string ParameterNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterName
        {
            get
            {
                return this.ParameterNameField;
            }
            set
            {
                this.ParameterNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndpointFailure", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class EndpointFailure : object
    {
        
        private string ElectronicSerialNumberField;
        
        private Ami_Common_Service.FailureReason FailureReasonField;
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ElectronicSerialNumber
        {
            get
            {
                return this.ElectronicSerialNumberField;
            }
            set
            {
                this.ElectronicSerialNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Ami_Common_Service.FailureReason FailureReason
        {
            get
            {
                return this.FailureReasonField;
            }
            set
            {
                this.FailureReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FailureReason", Namespace="http://www.itron.com/ami/2008/10/common")]
    public enum FailureReason : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TargetNotRegistered = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TargetNotFound = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommunicationError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SecurityFailure = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConfigurationError = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationNotSupported = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorResponse = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoResponse = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidIdentifier = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidTargetState = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PublishingError = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TooManyRequests = 12,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFault", Namespace="http://www.itron.com/ami/2008/10/security")]
    public partial class SecurityFault : object
    {
        
        private System.Guid IdField;
        
        private System.DateTime OccurredWhenField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime OccurredWhen
        {
            get
            {
                return this.OccurredWhenField;
            }
            set
            {
                this.OccurredWhenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusChangedInput", Namespace="http://www.itron.com/ami/2008/10/common")]
    public partial class StatusChangedInput : object
    {
        
        private Ami_Common_Service.RequestStatus RequestStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Ami_Common_Service.RequestStatus RequestStatus
        {
            get
            {
                return this.RequestStatusField;
            }
            set
            {
                this.RequestStatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.itron.com/ami/2008/10/common", ConfigurationName="Ami_Common_Service.RequestService")]
    public interface RequestService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itron.com/ami/2008/10/common/RequestService/GetRequestStatus", ReplyAction="http://www.itron.com/ami/2008/10/common/RequestService/GetRequestStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ami_Common_Service.ArgumentFault), Action="http://www.itron.com/ami/2008/10/common/RequestService/GetRequestStatusArgumentFa" +
            "ult", Name="ArgumentFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ami_Common_Service.RequestNotFoundFault), Action="http://www.itron.com/ami/2008/10/common/RequestService/GetRequestStatusRequestNot" +
            "FoundFault", Name="RequestNotFoundFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ami_Common_Service.OperationFault), Action="http://www.itron.com/ami/2008/10/common/RequestService/GetRequestStatusOperationF" +
            "ault", Name="OperationFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ami_Common_Service.SecurityFault), Action="http://www.itron.com/ami/2008/10/common/RequestService/GetRequestStatusSecurityFa" +
            "ult", Name="SecurityFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ami_Common_Service.TooManyConcurrentRequestsFault), Action="http://www.itron.com/ami/2008/10/common/RequestService/GetRequestStatusTooManyCon" +
            "currentRequestsFault", Name="TooManyConcurrentRequestsFault")]
        Ami_Common_Service.RequestStatus GetRequestStatus(Ami_Common_Service.RequestToken input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itron.com/ami/2008/10/common/RequestService/GetRequestStatus", ReplyAction="http://www.itron.com/ami/2008/10/common/RequestService/GetRequestStatusResponse")]
        System.Threading.Tasks.Task<Ami_Common_Service.RequestStatus> GetRequestStatusAsync(Ami_Common_Service.RequestToken input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itron.com/ami/2008/10/common/RequestService/CancelRequest", ReplyAction="http://www.itron.com/ami/2008/10/common/RequestService/CancelRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ami_Common_Service.ArgumentFault), Action="http://www.itron.com/ami/2008/10/common/RequestService/CancelRequestArgumentFault" +
            "", Name="ArgumentFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ami_Common_Service.RequestNotFoundFault), Action="http://www.itron.com/ami/2008/10/common/RequestService/CancelRequestRequestNotFou" +
            "ndFault", Name="RequestNotFoundFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ami_Common_Service.OperationFault), Action="http://www.itron.com/ami/2008/10/common/RequestService/CancelRequestOperationFaul" +
            "t", Name="OperationFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ami_Common_Service.SecurityFault), Action="http://www.itron.com/ami/2008/10/common/RequestService/CancelRequestSecurityFault" +
            "", Name="SecurityFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ami_Common_Service.TooManyConcurrentRequestsFault), Action="http://www.itron.com/ami/2008/10/common/RequestService/CancelRequestTooManyConcur" +
            "rentRequestsFault", Name="TooManyConcurrentRequestsFault")]
        void CancelRequest(Ami_Common_Service.RequestToken input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itron.com/ami/2008/10/common/RequestService/CancelRequest", ReplyAction="http://www.itron.com/ami/2008/10/common/RequestService/CancelRequestResponse")]
        System.Threading.Tasks.Task CancelRequestAsync(Ami_Common_Service.RequestToken input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface RequestServiceChannel : Ami_Common_Service.RequestService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class RequestServiceClient : System.ServiceModel.ClientBase<Ami_Common_Service.RequestService>, Ami_Common_Service.RequestService
    {
        
        public RequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Ami_Common_Service.RequestStatus GetRequestStatus(Ami_Common_Service.RequestToken input)
        {
            return base.Channel.GetRequestStatus(input);
        }
        
        public System.Threading.Tasks.Task<Ami_Common_Service.RequestStatus> GetRequestStatusAsync(Ami_Common_Service.RequestToken input)
        {
            return base.Channel.GetRequestStatusAsync(input);
        }
        
        public void CancelRequest(Ami_Common_Service.RequestToken input)
        {
            base.Channel.CancelRequest(input);
        }
        
        public System.Threading.Tasks.Task CancelRequestAsync(Ami_Common_Service.RequestToken input)
        {
            return base.Channel.CancelRequestAsync(input);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.itron.com/ami/2008/10/common", ConfigurationName="Ami_Common_Service.RequestStatusChangedService")]
    public interface RequestStatusChangedService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itron.com/ami/2008/10/common/RequestStatusChangedService/StatusChanged" +
            "", ReplyAction="http://www.itron.com/ami/2008/10/common/RequestStatusChangedService/StatusChanged" +
            "Response")]
        void StatusChanged(Ami_Common_Service.StatusChangedInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itron.com/ami/2008/10/common/RequestStatusChangedService/StatusChanged" +
            "", ReplyAction="http://www.itron.com/ami/2008/10/common/RequestStatusChangedService/StatusChanged" +
            "Response")]
        System.Threading.Tasks.Task StatusChangedAsync(Ami_Common_Service.StatusChangedInput input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface RequestStatusChangedServiceChannel : Ami_Common_Service.RequestStatusChangedService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class RequestStatusChangedServiceClient : System.ServiceModel.ClientBase<Ami_Common_Service.RequestStatusChangedService>, Ami_Common_Service.RequestStatusChangedService
    {
        
        public RequestStatusChangedServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void StatusChanged(Ami_Common_Service.StatusChangedInput input)
        {
            base.Channel.StatusChanged(input);
        }
        
        public System.Threading.Tasks.Task StatusChangedAsync(Ami_Common_Service.StatusChangedInput input)
        {
            return base.Channel.StatusChangedAsync(input);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
